### ISSUE TITLE
Timestamp for final frame duration.

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/TimecodeFPS#2]
Hi Asd-g, I have a 4 frame VRF GIF that I was testing and noticed that it's not possible to set the duration of the last frame because the number of timestamps [must match exactly the number of frames](https://github.com/Asd-g/TimecodeFPS/blob/master-1/src/timecodefps.cpp#L441). According to [this thread](https://forum.doom9.org/showthread.php?t=175277), having an extra timestamp is an acceptable way to set the duration of the last frame.

Here's the source:
![sWAeN6b](https://user-images.githubusercontent.com/3104705/147735722-8e155acf-12cb-43d3-b54a-ffd30e50ccd4.gif)

and here are the timestamps:

```
# timecode format v2
0
2000
5000
6000
11000
```

I added the final timestamp since both FFMS2 and FFMpeg only output the first 4 timestamps. Also FFMS2 and LWLibavVideoSource fail to convert this GIF to CFR properly. LWLibavVideoSource is mostly right except for the last frame not having the correct duration.

**Comment by Asd-g** [comment]
Hi, Can you test the latest version?

**Comment by Reel-Deal** [comment]
Hi, thank you for looking into this issue.

I can confirm the latest version works correctly; the last frame has the correct duration. However, when ``start=true`` I get this error in VirtualDub2 and AVSMeter: Avisynth open failure: System exception - Access Violation. The last version did not have this problem.

**Comment by Asd-g** [comment]
1.1.4 should be fine.

**Comment by Reel-Deal** [comment]
That fixes it :). Thanks for updating the wiki also. I added a note for the ``timescodes `` parameter: starting from v1.1.4, an extra timestamp sets the duration of the last frame (when specified).
